# Generated by Django 6.0.1 on 2026-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="clinical_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("operatoria", "Operatoria"),
                    ("endodoncia", "Endodoncia"),
                    ("periodoncia", "Periodoncia"),
                    ("cirugia", "Cirugía"),
                    ("protesis", "Prótesis"),
                    ("odontopediatria", "Odontopediatría"),
                    ("ortodoncia", "Ortodoncia"),
                ],
                max_length=20,
            ),
        ),
    ]
