# Generated by Django 6.0.1 on 2026-09-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_rename_document_id_to_dui"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="carnet",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de expediente/carnet interno de la clínica, si aplica.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("madre", "Madre"),
                    ("padre", "Padre"),
                    ("hermano_a", "Hermano/a"),
                    ("conyuge", "Cónyuge"),
                    ("hijo_a", "Hijo/a"),
                    ("otro", "Otro"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="patients/photos/"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de WhatsApp, si es distinto al teléfono principal.",
                max_length=20,
            ),
        ),
    ]
