# Generated by Django 6.0.1 on 2026-09-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_clinical_catalog_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='carnet',
        ),
    ]
