# Generated by Django 6.0.1 on 2026-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AclPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'permiso ACL',
                'verbose_name_plural': 'permisos ACL',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente supervisor'), ('estudiante', 'Estudiante'), ('recepcion', 'Recepción / Administrativo'), ('soporte', 'Soporte técnico')], default='estudiante', help_text='Identidad del usuario. Los permisos salen de la matriz ACL del rol.', max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='Los roles de sistema (admin, docente, …) no se eliminan.')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.aclpermission')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
    ]
