# Generated by Django 6.0.1 on 2026-09-16 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Diagnóstico del paciente.")),
                (
                    "treatment",
                    models.TextField(help_text="Tratamiento propuesto o aplicado."),
                ),
                (
                    "evolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas de evolución clínica a lo largo del tratamiento.",
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Estudiante que registró el diagnóstico/tratamiento.",
                        limit_choices_to={"role": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_clinical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Docente supervisor que validó este registro.",
                        limit_choices_to={"role": "docente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_clinical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
