# Generated by Django 6.0.1 on 2026-09-23 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_seed_clinical_catalog'),
        ('clinical_records', '0002_add_odontogram'),
        ('patients', '0007_remove_carnet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Diagnóstico del paciente.')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
                ('student', models.ForeignKey(help_text='Estudiante que registró el diagnóstico.', limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, help_text='Docente supervisor que validó este diagnóstico.', limit_choices_to={'role': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_evolutions', to='patients.patient')),
                ('student', models.ForeignKey(help_text='Estudiante que registró la nota de evolución.', limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_clinical_evolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records_treatments', to='catalogs.clinicalarea')),
                ('clinical_treatment', models.ForeignKey(help_text='Tipo de tratamiento del catálogo FOUEES.', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records_treatments', to='catalogs.clinicaltreatment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClinicalRecord',
        ),
    ]
