# Generated by Django 6.0.1 on 2026-09-23 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0003_diagnostico_evolucionclinica_tratamiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdontogramRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth', models.JSONField(default=list)),
                ('placa', models.BooleanField(default=False)),
                ('sangrado', models.BooleanField(default=False)),
                ('sarro', models.BooleanField(default=False)),
                ('visual_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogram_revisions', to=settings.AUTH_USER_MODEL)),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='clinical_records.odontogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
