# Generated by Django 6.0.1 on 2026-09-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='appointment_number',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Número de cita del paciente, correlativo por paciente.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reason',
            field=models.TextField(default='', help_text='Motivo de la cita/ingreso.'),
            preserve_default=False,
        ),
    ]
