# Generated by Django 6.0.1 on 2026-09-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_appointment_number_assignment_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='reason',
            field=models.TextField(blank=True, help_text='Motivo o nota al asignar.'),
        ),
    ]
