# Generated by Django 6.0.1 on 2026-09-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_reason_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='priority',
        ),
    ]
