# Generated by Django 6.0.1 on 2026-09-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_remove_assignment_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(help_text='Fecha y hora de inicio.')),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (90, '1 hora 30 minutos'), (120, '2 horas')], default=60)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='assignments.assignment')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
